### ISSUE TITLE
Max Timeout

### ISSUE THREAD

**Issue by jazozaya** [verifalia/verifalia-js-sdk#1]
Hi!

I am integrating your SDK into my app, so far so good, just wondering what the maximum timeout can be for the basic case below. I.e - Maximum amount of time before the promise gets rejected or resolved.

`const validation = await verifalia
    .emailValidations
    .submit('batman@gmail.com', true);`

Thanks

**Comment by verifalia** [comment]
Hello @jazozaya,

the maximum amount of time depends on the quality level you choose upon submitting (which falls back to the main account's default quality level if not specified - which itself has a factory default equals to _Standard_) as well as on the number of email addresses you are submitting.

For the case with just one email address, you can refer to the following values (redacted from https://verifalia.com/help/email-validations/result-quality-levels):

- _Standard_ quality has a maximum of ~5 seconds;
- _High_ quality has a maximum of ~50 seconds but up to 3 validation passes may be needed, depending on the address;
- _Extreme_ quality level has a maximum of ~2 minutes but up to 9 validation passes may be needed, depending on the address.

Hope this helps!

**Comment by jazozaya** [comment]
Yep! Thank you
